[2024-12-26T16:01:05.949+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2024-12-26T16:01:05.969+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: train_and_retrain_xgboost_pipeline.check_drift_and_retrain manual__2024-12-26T16:00:58.371900+00:00 [queued]>
[2024-12-26T16:01:05.980+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: train_and_retrain_xgboost_pipeline.check_drift_and_retrain manual__2024-12-26T16:00:58.371900+00:00 [queued]>
[2024-12-26T16:01:05.981+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2024-12-26T16:01:05.998+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): check_drift_and_retrain> on 2024-12-26 16:00:58.371900+00:00
[2024-12-26T16:01:06.005+0000] {standard_task_runner.py:72} INFO - Started process 860 to run task
[2024-12-26T16:01:06.009+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'train_and_retrain_xgboost_pipeline', 'check_drift_and_retrain', 'manual__2024-12-26T16:00:58.371900+00:00', '--job-id', '11', '--raw', '--subdir', 'DAGS_FOLDER/train_xgboost_pipeline.py', '--cfg-path', '/tmp/tmp2e966ri3']
[2024-12-26T16:01:06.012+0000] {standard_task_runner.py:105} INFO - Job 11: Subtask check_drift_and_retrain
[2024-12-26T16:01:06.029+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.10/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2024-12-26T16:01:06.066+0000] {task_command.py:467} INFO - Running <TaskInstance: train_and_retrain_xgboost_pipeline.check_drift_and_retrain manual__2024-12-26T16:00:58.371900+00:00 [running]> on host 42dc6dafdabb
[2024-12-26T16:01:06.148+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='train_and_retrain_xgboost_pipeline' AIRFLOW_CTX_TASK_ID='check_drift_and_retrain' AIRFLOW_CTX_EXECUTION_DATE='2024-12-26T16:00:58.371900+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-26T16:00:58.371900+00:00'
[2024-12-26T16:01:06.149+0000] {taskinstance.py:731} INFO - ::endgroup::
[2024-12-26T16:01:06.165+0000] {train_xgboost_pipeline.py:432} INFO - Starting drift detection and retraining if necessary...
[2024-12-26T16:01:06.247+0000] {train_xgboost_pipeline.py:313} INFO - Downloaded data/Ingestion/Financial_with_Sentiment.csv from MinIO to /tmp/Financial_with_Sentiment.csv
[2024-12-26T16:01:06.356+0000] {train_xgboost_pipeline.py:313} INFO - Downloaded data/Ingestion/Financial_with_Sentiment_pseudo.csv from MinIO to /tmp/Financial_with_Sentiment_pseudo.csv
[2024-12-26T16:01:06.735+0000] {logging_mixin.py:190} WARNING - /app/dags/train_xgboost_pipeline.py:443 DtypeWarning: Columns (2161) have mixed types. Specify dtype option on import or set low_memory=False.
[2024-12-26T16:01:07.180+0000] {logging_mixin.py:190} WARNING - /app/dags/train_xgboost_pipeline.py:444 DtypeWarning: Columns (2161) have mixed types. Specify dtype option on import or set low_memory=False.
[2024-12-26T16:01:07.257+0000] {logging_mixin.py:190} WARNING - /app/dags/train_xgboost_pipeline.py:403 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-12-26T16:01:08.719+0000] {logging_mixin.py:190} WARNING - /app/dags/train_xgboost_pipeline.py:403 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2024-12-26T16:01:08.724+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/usr/local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/app/dags/train_xgboost_pipeline.py", line 451, in check_drift_and_retrain
    current_X_scaled, current_y, _ = preprocess_data(current_df, target, reference_features=feature_columns)
  File "/app/dags/train_xgboost_pipeline.py", line 421, in preprocess_data
    X = df.drop(columns=[target_column])
  File "/usr/local/lib/python3.10/site-packages/pandas/core/frame.py", line 5581, in drop
    return super().drop(
  File "/usr/local/lib/python3.10/site-packages/pandas/core/generic.py", line 4788, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/generic.py", line 4830, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 7070, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "['ValueTrading'] not found in axis"
[2024-12-26T16:01:08.755+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=train_and_retrain_xgboost_pipeline, task_id=check_drift_and_retrain, run_id=manual__2024-12-26T16:00:58.371900+00:00, execution_date=20241226T160058, start_date=20241226T160105, end_date=20241226T160108
[2024-12-26T16:01:08.775+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2024-12-26T16:01:08.777+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 11 for task check_drift_and_retrain ("['ValueTrading'] not found in axis"; 860)
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
  File "/usr/local/lib/python3.10/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
  File "/usr/local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
  File "/usr/local/lib/python3.10/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
  File "/usr/local/lib/python3.10/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
  File "/usr/local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
  File "/usr/local/lib/python3.10/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
  File "/usr/local/lib/python3.10/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
  File "/app/dags/train_xgboost_pipeline.py", line 451, in check_drift_and_retrain
    current_X_scaled, current_y, _ = preprocess_data(current_df, target, reference_features=feature_columns)
  File "/app/dags/train_xgboost_pipeline.py", line 421, in preprocess_data
    X = df.drop(columns=[target_column])
  File "/usr/local/lib/python3.10/site-packages/pandas/core/frame.py", line 5581, in drop
    return super().drop(
  File "/usr/local/lib/python3.10/site-packages/pandas/core/generic.py", line 4788, in drop
    obj = obj._drop_axis(labels, axis, level=level, errors=errors)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/generic.py", line 4830, in _drop_axis
    new_axis = axis.drop(labels, errors=errors)
  File "/usr/local/lib/python3.10/site-packages/pandas/core/indexes/base.py", line 7070, in drop
    raise KeyError(f"{labels[mask].tolist()} not found in axis")
KeyError: "['ValueTrading'] not found in axis"
[2024-12-26T16:01:08.795+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2024-12-26T16:01:08.817+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-26T16:01:08.820+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
