[2025-01-01T16:03:13.770+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-01T16:03:13.841+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xgboost_drift_pipeline.retrain_model scheduled__2024-12-28T13:00:00+00:00 [queued]>
[2025-01-01T16:03:13.888+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xgboost_drift_pipeline.retrain_model scheduled__2024-12-28T13:00:00+00:00 [queued]>
[2025-01-01T16:03:13.890+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-01T16:03:13.942+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): retrain_model> on 2024-12-28 13:00:00+00:00
[2025-01-01T16:03:13.977+0000] {standard_task_runner.py:72} INFO - Started process 261 to run task
[2025-01-01T16:03:13.986+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'xgboost_drift_pipeline', 'retrain_model', 'scheduled__2024-12-28T13:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/train_xgboost_pipeline.py', '--cfg-path', '/tmp/tmpl5y0f5mh']
[2025-01-01T16:03:13.990+0000] {standard_task_runner.py:105} INFO - Job 47: Subtask retrain_model
[2025-01-01T16:03:14.024+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.10/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-01T16:03:14.134+0000] {task_command.py:467} INFO - Running <TaskInstance: xgboost_drift_pipeline.retrain_model scheduled__2024-12-28T13:00:00+00:00 [running]> on host 42dc6dafdabb
[2025-01-01T16:03:14.137+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.10/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-01T16:03:14.267+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xgboost_drift_pipeline' AIRFLOW_CTX_TASK_ID='retrain_model' AIRFLOW_CTX_EXECUTION_DATE='2024-12-28T13:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-12-28T13:00:00+00:00'
[2025-01-01T16:03:14.269+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-01T16:03:14.299+0000] {train_xgboost_pipeline.py:802} INFO - Starting retraining process...
[2025-01-01T16:03:14.374+0000] {train_xgboost_pipeline.py:674} INFO - Downloaded data/Ingestion/Financial_with_Sentiment_pseudo.csv from MinIO to /tmp/Financial_with_Sentiment_pseudo.csv
[2025-01-01T16:03:14.399+0000] {logging_mixin.py:190} WARNING - /app/dags/train_xgboost_pipeline.py:694 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-01-01T16:03:15.529+0000] {train_xgboost_pipeline.py:679} INFO - Uploaded /tmp/retrained_model_test.pkl to MinIO at data/Ingestion/retrained_model_test.pkl
[2025-01-01T16:03:15.532+0000] {train_xgboost_pipeline.py:827} INFO - Retrained model saved and uploaded.
[2025-01-01T16:03:15.549+0000] {train_xgboost_pipeline.py:833} INFO - Retrained Model Evaluation - MSE: 2562.47, R2: -0.46
[2025-01-01T16:03:15.556+0000] {logging_mixin.py:190} INFO - Retrained Model Metrics:
MSE: 2562.47
R2: -0.46
[2025-01-01T16:03:15.557+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-01T16:03:15.570+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-01T16:03:15.571+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=xgboost_drift_pipeline, task_id=retrain_model, run_id=scheduled__2024-12-28T13:00:00+00:00, execution_date=20241228T130000, start_date=20250101T160313, end_date=20250101T160315
[2025-01-01T16:03:15.612+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-01T16:03:15.649+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-01T16:03:15.652+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
