[2025-01-12T16:33:20.428+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-12T16:33:20.452+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xgboost_drift_pipeline.retrain_model scheduled__2025-01-01T17:00:00+00:00 [queued]>
[2025-01-12T16:33:20.464+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xgboost_drift_pipeline.retrain_model scheduled__2025-01-01T17:00:00+00:00 [queued]>
[2025-01-12T16:33:20.465+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-12T16:33:20.481+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): retrain_model> on 2025-01-01 17:00:00+00:00
[2025-01-12T16:33:20.492+0000] {standard_task_runner.py:72} INFO - Started process 263 to run task
[2025-01-12T16:33:20.496+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'xgboost_drift_pipeline', 'retrain_model', 'scheduled__2025-01-01T17:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/train_xgboost_pipeline.py', '--cfg-path', '/tmp/tmpdovun3bv']
[2025-01-12T16:33:20.499+0000] {standard_task_runner.py:105} INFO - Job 55: Subtask retrain_model
[2025-01-12T16:33:20.519+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.10/site-packages/***/settings.py:209 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-12T16:33:20.562+0000] {task_command.py:467} INFO - Running <TaskInstance: xgboost_drift_pipeline.retrain_model scheduled__2025-01-01T17:00:00+00:00 [running]> on host 42dc6dafdabb
[2025-01-12T16:33:20.566+0000] {logging_mixin.py:190} WARNING - /usr/local/lib/python3.10/site-packages/***/settings.py:470 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-01-12T16:33:20.660+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xgboost_drift_pipeline' AIRFLOW_CTX_TASK_ID='retrain_model' AIRFLOW_CTX_EXECUTION_DATE='2025-01-01T17:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-01T17:00:00+00:00'
[2025-01-12T16:33:20.661+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-12T16:33:20.678+0000] {train_xgboost_pipeline.py:802} INFO - Starting retraining process...
[2025-01-12T16:33:20.713+0000] {train_xgboost_pipeline.py:674} INFO - Downloaded data/Ingestion/Financial_with_Sentiment_pseudo.csv from MinIO to /tmp/Financial_with_Sentiment_pseudo.csv
[2025-01-12T16:33:20.729+0000] {logging_mixin.py:190} WARNING - /app/dags/train_xgboost_pipeline.py:694 SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
[2025-01-12T16:33:24.060+0000] {train_xgboost_pipeline.py:679} INFO - Uploaded /tmp/retrained_model_test.pkl to MinIO at data/Ingestion/retrained_model_test.pkl
[2025-01-12T16:33:24.061+0000] {train_xgboost_pipeline.py:827} INFO - Retrained model saved and uploaded.
[2025-01-12T16:33:24.067+0000] {train_xgboost_pipeline.py:833} INFO - Retrained Model Evaluation - MSE: 2562.47, R2: -0.46
[2025-01-12T16:33:24.069+0000] {logging_mixin.py:190} INFO - Retrained Model Metrics:
MSE: 2562.47
R2: -0.46
[2025-01-12T16:33:24.071+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-12T16:33:24.083+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-12T16:33:24.085+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=xgboost_drift_pipeline, task_id=retrain_model, run_id=scheduled__2025-01-01T17:00:00+00:00, execution_date=20250101T170000, start_date=20250112T163320, end_date=20250112T163324
[2025-01-12T16:33:24.131+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-12T16:33:24.154+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-12T16:33:24.169+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
